package ru.bmstu.iu9.andruxa.kartinki

const val API_KEY = "v2/cUd1Z1hFbWk4WGVpUmlkNmVqQUwzdE1ub3BrUDBUSm4vMzE0OTExNjg0L2N1c3RvbWVyLzQvVEhVNC1sdFBacVdEaW43NThkOUtGNmVHSi16dk5ZQmlDYUJkREREQl9NbzVIZVVfb1NRX3hQRWpRNGRiYzlkMFRGdnhtM1UxX3k0b2VrcHVwM2hUUWM5eTNnNUNfWF9YMURfSDNyLTd2QjljbmZQN2dyVkctMlFGMnZ4SDZhRjlMRnJTeXVteDdIWmhRSHZVM3FMenZlNHBVZjV5czZqVXJZay1HSmlsY2cyWExIdUkwSEE2WnB4c2E5clNjYWszQ044ZWprNk5ZVHhqRU42QW5tQW9hdy9ra1VsWGQ1WW1SM0dRMThkMGNEcU9B"

val LANGUAGE_CODES: List<String> = listOf("ru", "en")

enum class COLORS {
  PURPLE,
  RED,
}

enum class THEMES {
  LIGHT,
  DARK,
  SYSTEM,
}


